---
- name: Managing users for ethenhunt
  hosts: ethenhunt
  vars:
    servers_to_monitor: "{{ groups['ethenhunt'] }}"
  tasks:
    - user:
        name: "{{ username }}"
        shell: /bin/bash
        generate_ssh_key: true
        state: present
    - name: Get user Public file
      fetch:
        src: "/home/{{ username }}/.ssh/id_rsa.pub"
        dest: "/tmp/ethenhunt/{{ username }}.pub"
        flat: yes
    - user:
        name: "{{ adminuser }}"
        shell: /bin/bash
        generate_ssh_key: true
        state: present
    - template:
        src: "./config.j2"
        dest: "/home/{{ username }}/.ssh/config"
        owner: "{{ username }}"
        mode: 0600

- name: Managing users for Dev Ninja
  hosts: devninja
  vars:
    servers_to_monitor: "{{ groups['devninja'] }}"
  tasks:
    - user:
        name: "{{ username }}"
        shell: /bin/bash
        generate_ssh_key: true
        state: present
    - user:
        name: "{{ adminuser }}"
        shell: /bin/bash
        generate_ssh_key: true
        state: present
    - template:
        src: "./config.j2"
        dest: "/home/{{ username }}/.ssh/config"
        owner: "{{ username }}"
        mode: 0600