---
- name: Managing users on system
  hosts: all

  tasks:
    - user:
        name: "{{ username }}"
        shell: /bin/bash
        generate_ssh_key: true
        state: present
    - debug:
        msg : "Creating sshconfig file for {{ item }}"
      with_items: "{{ usergroup }}"  
    - template:
        src: ./config.j2
        dest: "/home/{{ username }}/.ssh/config"
        owner: "{{ username }}"
        mode: 0600