---
- name: Managing users on system
  hosts: all
  tasks:
    - debug:
        msg : "Creating user {{ username }}"
    - user:
        name: "{{ username }}"
        shell: /bin/bash
        generate_ssh_key: true
        state: present
